//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMatetMob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public int code_affect { get; set; }
        public int code_article { get; set; }
        public int code_service { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Service Service { get; set; }
    }
}
