//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMatetMob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caracteristique()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int code_caract { get; set; }
        public double prix { get; set; }
        public int quantité { get; set; }
        public string etat { get; set; }
        public System.DateTime date_acquisition { get; set; }
        public System.DateTime date_mis_ser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
    }
}
