//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMatetMob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_MaterielEntitie : DbContext
    {
        public Gestion_MaterielEntitie()
            : base("name=Gestion_MaterielEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affectation> Affectations { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Caracteristique> Caracteristiques { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Direction> Directions { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
